name: Scheduler Test

on:
  schedule:
    - cron: "47 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduler működik
        run: echo "A scheduler működik."
